### ISSUE TITLE
Problem during installation of omaha-server

### ISSUE THREAD

**Issue by Nialito** [Crystalnix/omaha-server#359]
Hello. 

While running the `sudo make up` command, I had a problem in step seven.
```
root@thaldar90:~/omaha-server# sudo make up
docker-compose -f docker-compose.dev.yml -p dev build web
Building web
Step 1/7 : FROM crystalnix/omaha-server-base:alpine
 ---> e4988a4d885b
Step 2/7 : RUN pipenv install --system --dev
 ---> Using cache
 ---> 3875c9d0e14f
Step 3/7 : ADD . $omaha
 ---> Using cache
 ---> bba20cf115ef
Step 4/7 : RUN   mkdir /etc/nginx/sites-enabled/ &&   rm /etc/filebeat/filebeat.                                                                                        yml &&   rm /etc/nginx/conf.d/default.conf &&   rm /etc/nginx/nginx.conf &&   rm                                                                                         /etc/supervisord.conf &&   ln -s /srv/omaha/conf/nginx.conf /etc/nginx/ &&   ln                                                                                         -s /srv/omaha/conf/nginx-app.conf /etc/nginx/sites-enabled/ &&   ln -s /srv/oma                                                                                        ha/conf/inflate_request.lua /var/lib/nginx &&   ln -s /srv/omaha/conf/supervisor                                                                                        d.conf /etc/ &&   ln -s /srv/omaha/conf/filebeat.yml /etc/filebeat/ &&   chmod g                                                                                        o-w /etc/filebeat/filebeat.yml
 ---> Using cache
 ---> ec18a12d9f71
Step 5/7 : EXPOSE 80
 ---> Using cache
 ---> cb563c34c499
Step 6/7 : EXPOSE 8080
 ---> Using cache
 ---> 894360dafdb8
Step 7/7 : CMD ["paver", "docker_run"]
 ---> Using cache
 ---> a4bd1b40fc2c
Successfully built a4bd1b40fc2c
Successfully tagged dev_web:latest
pipenv run paver up_local_dev_server
Traceback (most recent call last):
  File "/usr/bin/paver", line 5, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/paver/tasks.py", line 883, in main
    _launch_pavement(args)
  File "/usr/lib/python2.7/dist-packages/paver/tasks.py", line 851, in _launch_p                                                                                        avement
    exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)
  File "pavement.py", line 157
    sh(f'rsyslogd -f {rsyslog_conf_path}')
                                        ^
SyntaxError: invalid syntax
Makefile:46: recipe for target 'up' failed
make: *** [up] Error 1
```

Operating system: `Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-74-generic x86_64)`

All necessary Python versions are installed:
```
root@thaldar90:~/omaha-server# python --version
Python 2.7.17
root@thaldar90:~/omaha-server# python3 --version
Python 3.6.9
root@thaldar90:~/omaha-server# python3.7 --version
Python 3.7.5
root@thaldar90:~/omaha-server# python3.8 --version
Python 3.8.0
root@thaldar90:~/omaha-server# pip --version
pip 19.3.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
root@thaldar90:~/omaha-server# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```
All packages that needed to be installed according to the instructions were installed without problems:
```
root@thaldar90:~/omaha-server# docker --version
Docker version 18.09.7, build 2d0083d
root@thaldar90:~/omaha-server# pipenv --version
pipenv, version 2018.11.26
root@thaldar90:~/omaha-server# docker-compose --version
docker-compose version 1.25.1, build a82fef0
```

I also tried changing the link to Python:
```
root@thaldar90:/usr/bin# sudo ln -sfn python3.6 /usr/bin/python
root@thaldar90:/usr/bin# sudo ln -sfn python3.6 /usr/bin/python2
```

But, unfortunately, this did not solve the problem:
```
root@thaldar90:~/omaha-server# python --version
Python 3.6.9
root@thaldar90:~/omaha-server# python2 --version
Python 3.6.9
root@thaldar90:~/omaha-server# sudo make up
docker-compose -f docker-compose.dev.yml -p dev build web
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
ModuleNotFoundError: No module named 'compose'
Makefile:10: recipe for target 'build-dev-web' failed
make: *** [build-dev-web] Error 1
```
I will be very grateful for every response!

**Comment by Nialito** [comment]
The problem was solved by rewriting the string `sh(f'ryslogd -f {rsyslog_conf_path}')`.
