### ISSUE TITLE
How to change port 9090 to 80 or 443

### ISSUE THREAD

**Issue by quyen194** [Crystalnix/omaha-server#78]
Hi, I have problem in request url: domain:9090
I need to hide port in request url so I need to change 9090 to default http port
How to do that? I try change in config file but not success :(

**Comment by avli** [comment]
I think the simplest way is to run the application with command

```console
django-admin runserver localhost:80
```

On the the hand this approach may be not a good practice in general. I believe, the best way to change the application access port is to use nginx and proxy all requests on port 80 to port 9090.

**Comment by quyen194** [comment]
Thanks I would try,
Now I can't build omaha server :(
I tried fresh build on new ubuntu but not success :((
I think crystalnix need to re-check lastest source with new machine :(

**Comment by vivekgalatage** [comment]
When I run ```django-admin runserver localhost:80``` from the root directory of project checkout I get following error:

```
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 279, in execute
    saved_locale = translation.get_language()
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 154, in get_language
    return _trans.get_language()
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 52, in __getattr__
    if settings.USE_I18N:
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 47, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by avli** [comment]
@vivekgalatage You may try something like this

```console
./manage.py runserver --settings=omaha_server.settings_local
```
